Improve test suite (with README)
still based on `Makefile` and `diff`, but run and report each test
individually.

This is some yak shaving towards running tests with only capturing IO,
and eventually comparing it to compiled code.

diff --git a/src/test/Makefile b/src/test/Makefile
--- a/src/test/Makefile
+++ b/src/test/Makefile
@@ -2,38 +2,36 @@
 
 # This works with bash
 
-ASC=../main.native
+ASC=../asc
 ASC_FLAGS=-t -d
-# with the compiler
-all:
-	rm -f result
-	$(ASC) $(ASC_FLAGS) bank.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) bank_ordered.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) control.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) literals.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) numericops.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) bitops.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) relationalops.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) concat.as >> result 2>&1	
-	$(ASC) $(ASC_FLAGS) duplicatefield.as >> result 2>&1 || true
-	$(ASC) $(ASC_FLAGS) nonlinearpat.as >> result 2>&1 || true
-	$(ASC) $(ASC_FLAGS) typedef.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) type_equiv.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) quicksort.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) hoare.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) bankex.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) counter.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) testwhile.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) objects.as >> result 2>&1
-	$(ASC) $(ASC_FLAGS) overflow.as >> result 2>&1 || true
-	$(ASC) $(ASC_FLAGS) menhirbug.as >> result 2>&1 || true
 
-	diff result result.ok
+TESTS:=$(basename $(wildcard *.as))
 
-# refresh
-current:
-	rm -f result
-	make all 
+all: stats
+
+%.out : %.as $(ASC)
+	$(ASC) $(ASC_FLAGS) $< > $@ 2>&1 || true
+
+%.diff : %.out %.ok
+	diff -u $*.out $*.ok | tee $@ || true
+
+%.refresh : %.out
+	cat $*.out > $*.ok
+
+stats: $(addsuffix .diff,$(TESTS))
+	@failed=$$(find $^ -not -empty -printf "%f\n"|sed -e s,\.diff,,); \
+	if [ -z "$$failed" ]; \
+	then echo "All passed!"; \
+	else echo "Failed tests: $$failed"; exit 1; \
+	fi
+
+# refresh all
+current: $(addsuffix .refresh, $(TESTS))
+accept: current
 
 clean:
-	rm -f result
+	rm -f $(addsuffix .diff, $(TESTS)) $(addsuffix .out, $(TESTS))
+
+.PHONY: stats current accept all # $(addsuffix .refresh, $(TESTS))
+
+FORCE:
