fix: allow `grep` and other `bash` failures in `approvals?` CI steps (#5592)
# What goes wrong in approvals?

The scripts got thrown off the track by a non-match of `grep`.

Also fix the success conditions for `verify-common-gc` and
`verify-main-tests`. These should *always* run, in order to make the
branch merge conditions reliable. (Skipped steps count as success!)

With this:
<img width="863" height="113" alt="Screenshot 2025-10-22 at 14 19 16"
src="https://github.com/user-attachments/assets/9d116af2-2371-4371-81f2-9377bef5f2d7"
/>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -129,17 +129,40 @@ jobs:
 
   verify-common-gc:
     needs: [common-tests, gc-tests]
+    if: ${{ always() }}  # run even if dependencies failed/skipped/cancelled
     runs-on: ubuntu-latest
     steps:
+      - name: Show dependency results
+        run: |
+          echo common-tests: ${{ needs.common-tests.result }}
+          echo gc-tests: ${{ needs.gc-tests.result }}
+      - name: Fail if any dependency did not succeed
+        run: |
+          if ${{ needs.common-tests.result != 'success' || needs.gc-tests.result != 'success' }}; then
+            echo "One or more dependencies failed/skipped/cancelled."
+            exit 1
+          fi
       - name: Common and GC tests passed
+        if: ${{ success() }}
         run: echo "Common and GC tests completed successfully."
 
   verify-main-tests:
     needs: tests
+    if: ${{ always() }}  # run even if dependencies failed/skipped/cancelled
     runs-on: ubuntu-latest
     steps:
-      - name: Main tests passed
-        run: echo "Main tests completed successfully."
+      - name: Show dependency results
+        run: |
+          echo tests: ${{ needs.tests.result }}
+      - name: Fail if any dependency did not succeed
+        run: |
+          if ${{ needs.tests.result != 'success' }}; then
+            echo "One or more dependencies failed/skipped/cancelled."
+            exit 1
+          fi
+      - name: Main test passed
+        if: ${{ success() }}
+        run: echo "Main test completed successfully."
 
   autoclose:
     if: github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.base.ref == 'master' && contains(github.event.pull_request.labels.*.name, 'autoclose')
@@ -168,8 +191,10 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
+          set +e
           gh pr diff ${{ github.event.pull_request.number }} | grep -E '^--- a/Changelog.md$' \
           && gh pr review ${{ github.event.pull_request.number }} --approve --body 'A change to `Changelog.md`? I can handle that!'
+          true
 
 # Handles open PRs filed by `dependabot[bot]` that carry the `dependencies` label. The single changed file must be `doc/docusaurus/package-lock.json`. If so, the PR gets approved with a comment.
   approvals2:
@@ -183,8 +208,10 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
+          set +e
           gh pr diff ${{ github.event.pull_request.number }} | grep -E '^--- a/doc/docusaurus/package-lock.json$' \
           && gh pr review ${{ github.event.pull_request.number }} --approve --body 'A change to `doc/docusaurus/package-lock.json`? I can handle that!'
+          true
 
 # Handles open PRs filed by the GH automation bot (not checked here yet) that carry the `automerge-squash` label. The single changed file must be `flake.lock`. If so, the PR gets approved with a comment, auto-merge activated and the label removed.
   approvals3:
@@ -197,12 +224,13 @@ jobs:
       - name: Hand out approvals
         env:
           GH_TOKEN: ${{ github.token }}
-          OUTPUT: ${{ toJson(github.event.pull_request) }}
         run: |
+          set +e
           gh pr diff ${{ github.event.pull_request.number }} | grep -E '^--- a/flake.lock$' \
           && gh pr review ${{ github.event.pull_request.number }} --approve --body 'A change to `flake.lock`? I can handle that!' \
           && gh pr merge ${{ github.event.pull_request.number }} --squash --auto \
           && gh pr edit ${{ github.event.pull_request.number }} --remove-label 'automerge-squash'
+          true
 
 # Note: the above 3 steps can be joined to just one step by factoring out the common `if:` condition fragments,
 #       merging the `run:` parts and and re-adding the differing conditions as a prefix to the pipelines using the `${{ <condition> }}` syntax.
